services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  php56:
    container_name: php56
    image: php56
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    networks:
      - proxy
    volumes:
      - ./html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.webserver.rule=Host(`webserver.docker.localhost`)"
      - "traefik.http.routers.webserver.entrypoints=web"

  mysql:
    container_name: mysql
    image: mysql:5.7.44
    restart: always
    ports:
      - 3306:3306
    networks:
      - proxy
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app123456
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --explicit_defaults_for_timestamp

  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin"
    restart: always
    networks:
      - proxy
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    environment:
      - PMA_ARBITRARY=1

networks:
  proxy:
    external: true
